# Generated by Django 4.2.26 on 2025-11-24 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='complete',
            new_name='complete_state',
        ),
        migrations.RenameField(
            model_name='target',
            old_name='complete',
            new_name='complete_state',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='mission_name',
        ),
        migrations.RemoveField(
            model_name='target',
            name='notes',
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='cats.target')),
            ],
        ),
    ]
